[colors]
[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.normal]
black   = "#000000"
red     = "#7c7c7c"
green   = "#8b8b8b"
yellow  = "#a0a0a0"
blue    = "#686868"
magenta = "#747474"
cyan    = "#868686"
white   = "#b9b9b9"

[colors.bright]
black   = "#525252"
red     = "#7c7c7c"
green   = "#8b8b8b"
yellow  = "#a0a0a0"
blue    = "#686868"
magenta = "#747474"
cyan    = "#868686"
white   = "#ffffff"

[colors.cursor]
text   = "#000000"
cursor = "#ffffff"
